version: '2.4'

networks:
  main:

services:
  database:
    image: postgres:${POSTGRES_VERSION}
    container_name: bts-api-database
    networks:
      - main
    ports:
      - ${PORT_DATABASE}:5432
    volumes:
      - ./.docker/init/database:/docker-entrypoint-initdb.d
      - ./.docker/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    mem_limit: 1g

  mail:
    image: djfarrelly/maildev
    container_name: bts-api-mail
    networks:
      - main
    ports:
      - ${PORT_MAIL_SMTP}:25
      - ${PORT_MAIL_UI}:80
    restart: on-failure
    mem_limit: 50m

  api:
    build:
      context: quarkus-api
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: bts-api
    networks:
      - main
    ports:
      - ${PORT_API}:8080
    environment:
      QUARKUS_PROFILE: dev
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: backstage
    restart: no
    mem_limit: 512m
